// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcMX9n2L8EuWq7ewy0x43nMDoGNRYMzlE',
    appId: '1:683962247948:web:98dd2dca1518d8d95b3729',
    messagingSenderId: '683962247948',
    projectId: 'toice-app',
    authDomain: 'toice-app.firebaseapp.com',
    storageBucket: 'toice-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJiK2MlJT1rPWxrK1hDId9tLaJCnDMdtY',
    appId: '1:683962247948:android:1fc55eebff3169b75b3729',
    messagingSenderId: '683962247948',
    projectId: 'toice-app',
    storageBucket: 'toice-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9jwS4KpOf5JLSCt8VrN1xTKXelNK44c',
    appId: '1:683962247948:ios:93136dd18afc86df5b3729',
    messagingSenderId: '683962247948',
    projectId: 'toice-app',
    storageBucket: 'toice-app.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

}